import React, { useMemo } from 'react';
import { motion } from 'framer-motion';
import {
    TrendingUp,
    Droplets,
    Zap,
    Wallet,
    ShieldCheck,
    Coins,
    Leaf,
    ArrowUpRight
} from 'lucide-react';

const EconomicImpact = ({ sensorData, ndviValue = 0.65 }) => {
    // Simulated calculations based on real sensor trends
    // In a real app, these would come from historical comparisons in the backend
    const metrics = useMemo(() => {
        const moisture = sensorData?.soil_moisture || 45;
        const waterSaved = Math.round(moisture * 2.4 * 10); // Litres saved by precision
        const fertilizerSaved = 12.5; // kg saved by variable rate application
        const yieldBoost = ndviValue > 0.6 ? 18.4 : 12.2; // % improvement vs regional average
        const incomeGain = Math.round(yieldBoost * 450); // Estimated extra INR per acre
        const riskScore = Math.round(100 - (moisture < 20 ? 40 : 10)); // Risk reduction score

        return {
            water: waterSaved,
            fertilizer: fertilizerSaved,
            yield: yieldBoost,
            income: incomeGain,
            risk: riskScore
        };
    }, [sensorData, ndviValue]);

    const cards = [
        {
            title: "Water Saved",
            value: `${metrics.water} L`,
            sub: "Precision Irrigation Efficiency",
            icon: <Droplets className="text-blue-400" />,
            color: "blue",
            delay: 0
        },
        {
            title: "Fertilizer Saved",
            value: `${metrics.fertilizer} kg`,
            sub: "Variable Rate Optimization",
            icon: <Zap className="text-amber-400" />,
            color: "amber",
            delay: 0.1
        },
        {
            title: "Yield Improvement",
            value: `+${metrics.yield}%`,
            sub: "Vs. Regional Average",
            icon: <TrendingUp className="text-emerald-400" />,
            color: "emerald",
            delay: 0.2
        },
        {
            title: "Income Gain Est.",
            value: `₹${metrics.income}`,
            sub: "Projected Extra Revenue/Acre",
            icon: <Coins className="text-yellow-400" />,
            color: "yellow",
            delay: 0.3
        }
    ];

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div className="space-y-1">
                    <h3 className="text-xl font-black text-slate-900 dark:text-white uppercase tracking-tight flex items-center gap-2">
                        <Wallet className="w-5 h-5 text-emerald-400" />
                        Economic Impact Dashboard
                    </h3>
                    <p className="text-[10px] text-slate-500 font-bold uppercase tracking-[0.2em]">Quantifiable Value Generated by AI</p>
                </div>
                <div className="flex items-center gap-2 px-3 py-1.5 bg-emerald-500/10 border border-emerald-500/20 rounded-full">
                    <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                    <span className="text-[9px] font-black text-emerald-400 uppercase tracking-widest">ROI Verified</span>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                {cards.map((card, i) => (
                    <motion.div
                        key={i}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: card.delay }}
                        className="group relative"
                    >
                        <div className="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent rounded-[2rem] border border-slate-200 dark:border-white/10 group-hover:border-white/20 transition-all duration-500" />
                        <div className="relative p-6 space-y-4">
                            <div className="flex items-center justify-between">
                                <div className={`p-2.5 rounded-2xl bg-${card.color}-500/10 border border-${card.color}-500/20`}>
                                    {card.icon}
                                </div>
                                <ArrowUpRight className="w-4 h-4 text-slate-600 group-hover:text-white transition-colors" />
                            </div>
                            <div>
                                <h4 className="text-[9px] font-black text-slate-500 uppercase tracking-widest mb-1">{card.title}</h4>
                                <div className="flex items-baseline gap-2">
                                    <span className="text-2xl font-black text-slate-900 dark:text-white">{card.value}</span>
                                </div>
                                <p className="text-[10px] text-slate-500 font-medium mt-1">{card.sub}</p>
                            </div>
                        </div>
                    </motion.div>
                ))}
            </div>

            <div className="bg-gradient-to-br from-emerald-500/10 via-blue-500/5 to-transparent border border-slate-200 dark:border-white/10 rounded-[2.5rem] p-6">
                <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                    <div className="flex items-center gap-5">
                        <div className="relative w-16 h-16">
                            <svg className="w-full h-full -rotate-90" viewBox="0 0 36 36">
                                <circle cx="18" cy="18" r="16" fill="none" stroke="currentColor" strokeWidth="3" className="text-white/5" />
                                <motion.circle
                                    cx="18" cy="18" r="16" fill="none" stroke="currentColor" strokeWidth="3"
                                    className="text-emerald-500"
                                    strokeDasharray={`${metrics.risk}, 100`}
                                    initial={{ strokeDashoffset: 100 }}
                                    animate={{ strokeDashoffset: 0 }}
                                    transition={{ duration: 1.5, ease: "easeOut" }}
                                />
                            </svg>
                            <div className="absolute inset-0 flex flex-col items-center justify-center">
                                <span className="text-sm font-black text-slate-900 dark:text-white">{metrics.risk}%</span>
                            </div>
                        </div>
                        <div>
                            <h4 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-tight mb-0.5">Risk Reduction Score</h4>
                            <p className="text-xs text-slate-500 font-medium">Predictive Intelligence mitigating climate and pest threats.</p>
                        </div>
                    </div>

                    <div className="flex items-center gap-3">
                        <div className="h-12 w-px bg-slate-100 dark:bg-white/10 shadow-sm dark:shadow-none hidden md:block mx-4" />
                        <div className="text-right">
                            <div className="flex items-center justify-end gap-2 text-emerald-400 font-black text-xs uppercase mb-1">
                                <Leaf className="w-3 h-3" />
                                Environmentally Net-Positive
                            </div>
                            <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">Calculated by Let's Go 3.0 Real-time Engine</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default EconomicImpact;
